name: Build and Deploy Docker Image

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build bundle
        run: yarn build

      #- name: Setup Debug Session
      #  uses: csexton/debugger-action@master

      - name: Create Distribution
        run: yarn release

  # tag-stable-version:
  #   #needs: docker-image
  #   runs-on: ubuntu-latest
  #   if: ${{ success() }}

  #   steps:

  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   - name: Get current date
  #     id: date
  #     run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H-%M-%S')"

  #   - name: Create a new Git tag
  #     uses: rickstaa/action-create-tag@v1
  #     with:
  #       tag: ${{ steps.date.outputs.date }}
  #       message: "Latest release"
